#############################################################################
# Makefile for building: qmodbus
# Generated by qmake (3.1) (Qt 5.15.13)
# Project:  qmodbus.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile qmodbus.pro -qtconf /usr/lib/x86_64-linux-gnu/qt5/qt.conf -early QMAKE_CC=x86_64-linux-gnu-gcc QMAKE_CXX=x86_64-linux-gnu-g++ QMAKE_LINK=x86_64-linux-gnu-g++ QMAKE_STRIP=x86_64-linux-gnu-strip QMAKE_QMAKE=/usr/bin/x86_64-linux-gnu-qmake PKG_CONFIG=x86_64-linux-gnu-pkg-config -before
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = x86_64-linux-gnu-gcc
CXX           = x86_64-linux-gnu-g++
DEFINES       = -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I3rdparty/libmodbus -I3rdparty/libmodbus/src -Isrc -Isrc/core -Isrc/ui -Isrc/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qmodbus0.1.0
DISTDIR = /home/mengin/İndirilenler/qmodbus-master/.tmp/qmodbus0.1.0
LINK          = x86_64-linux-gnu-g++
LFLAGS        = 
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Charts.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5SerialPort.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Concurrent.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = x86_64-linux-gnu-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/DeviceConfigDialog.cpp \
		src/core/ModbusDevice.cpp \
		src/core/ModbusRegister.cpp \
		src/core/ModbusConnection.cpp \
		src/ui/ConnectionSettingsWidget.cpp \
		src/ui/RegisterTableModel.cpp \
		src/ui/RegisterSetupDialog.cpp \
		src/utils/Logger.cpp \
		src/utils/Settings.cpp \
		src/utils/DataLogger.cpp \
		3rdparty/libmodbus/src/modbus.c \
		3rdparty/libmodbus/src/modbus-data.c \
		3rdparty/libmodbus/src/modbus-tcp.c \
		src/tcpipsettingswidget.cpp \
		src/ipaddressctrl.cpp \
		src/iplineedit.cpp qrc_qmodbus.cpp \
		moc_mainwindow.cpp \
		moc_DeviceConfigDialog.cpp \
		moc_ModbusDevice.cpp \
		moc_ModbusRegister.cpp \
		moc_ModbusConnection.cpp \
		moc_ConnectionSettingsWidget.cpp \
		moc_RegisterTableModel.cpp \
		moc_RegisterSetupDialog.cpp \
		moc_Logger.cpp \
		moc_Settings.cpp \
		moc_DataLogger.cpp \
		moc_tcpipsettingswidget.cpp \
		moc_ipaddressctrl.cpp \
		moc_iplineedit.cpp
OBJECTS       = main.o \
		mainwindow.o \
		DeviceConfigDialog.o \
		ModbusDevice.o \
		ModbusRegister.o \
		ModbusConnection.o \
		ConnectionSettingsWidget.o \
		RegisterTableModel.o \
		RegisterSetupDialog.o \
		Logger.o \
		Settings.o \
		DataLogger.o \
		modbus.o \
		modbus-data.o \
		modbus-tcp.o \
		tcpipsettingswidget.o \
		ipaddressctrl.o \
		iplineedit.o \
		qrc_qmodbus.o \
		moc_mainwindow.o \
		moc_DeviceConfigDialog.o \
		moc_ModbusDevice.o \
		moc_ModbusRegister.o \
		moc_ModbusConnection.o \
		moc_ConnectionSettingsWidget.o \
		moc_RegisterTableModel.o \
		moc_RegisterSetupDialog.o \
		moc_Logger.o \
		moc_Settings.o \
		moc_DataLogger.o \
		moc_tcpipsettingswidget.o \
		moc_ipaddressctrl.o \
		moc_iplineedit.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		deployment.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		qmodbus.pro src/mainwindow.h \
		src/DeviceConfigDialog.h \
		src/core/ModbusDevice.h \
		src/core/ModbusRegister.h \
		src/core/ModbusConnection.h \
		src/ui/ConnectionSettingsWidget.h \
		src/ui/RegisterTableModel.h \
		src/ui/RegisterSetupDialog.h \
		src/utils/ModbusTypes.h \
		src/utils/Logger.h \
		src/utils/Settings.h \
		src/utils/DataLogger.h \
		3rdparty/libmodbus/src/modbus.h \
		src/imodbus.h \
		src/tcpipsettingswidget.h \
		src/ipaddressctrl.h \
		src/iplineedit.h src/main.cpp \
		src/mainwindow.cpp \
		src/DeviceConfigDialog.cpp \
		src/core/ModbusDevice.cpp \
		src/core/ModbusRegister.cpp \
		src/core/ModbusConnection.cpp \
		src/ui/ConnectionSettingsWidget.cpp \
		src/ui/RegisterTableModel.cpp \
		src/ui/RegisterSetupDialog.cpp \
		src/utils/Logger.cpp \
		src/utils/Settings.cpp \
		src/utils/DataLogger.cpp \
		3rdparty/libmodbus/src/modbus.c \
		3rdparty/libmodbus/src/modbus-data.c \
		3rdparty/libmodbus/src/modbus-tcp.c \
		src/tcpipsettingswidget.cpp \
		src/ipaddressctrl.cpp \
		src/iplineedit.cpp
QMAKE_TARGET  = qmodbus
DESTDIR       = 
TARGET        = qmodbus


first: all
####### Build rules

qmodbus: ui_mainwindow.h ui_ConnectionSettingsWidget.h ui_RegisterSetupDialog.h ui_tcpipsettingswidget.h ui_ipaddressctrl.h ui_DeviceConfigDialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qmodbus.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		deployment.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		qmodbus.pro \
		data/qmodbus.qrc
	$(QMAKE) -o Makefile qmodbus.pro -qtconf /usr/lib/x86_64-linux-gnu/qt5/qt.conf -early QMAKE_CC=x86_64-linux-gnu-gcc QMAKE_CXX=x86_64-linux-gnu-g++ QMAKE_LINK=x86_64-linux-gnu-g++ QMAKE_STRIP=x86_64-linux-gnu-strip QMAKE_QMAKE=/usr/bin/x86_64-linux-gnu-qmake PKG_CONFIG=x86_64-linux-gnu-pkg-config -before
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
deployment.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
qmodbus.pro:
data/qmodbus.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile qmodbus.pro -qtconf /usr/lib/x86_64-linux-gnu/qt5/qt.conf -early QMAKE_CC=x86_64-linux-gnu-gcc QMAKE_CXX=x86_64-linux-gnu-g++ QMAKE_LINK=x86_64-linux-gnu-g++ QMAKE_STRIP=x86_64-linux-gnu-strip QMAKE_QMAKE=/usr/bin/x86_64-linux-gnu-qmake PKG_CONFIG=x86_64-linux-gnu-pkg-config -before

qmake_all: FORCE


all: Makefile qmodbus

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents data/qmodbus.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/mainwindow.h src/DeviceConfigDialog.h src/core/ModbusDevice.h src/core/ModbusRegister.h src/core/ModbusConnection.h src/ui/ConnectionSettingsWidget.h src/ui/RegisterTableModel.h src/ui/RegisterSetupDialog.h src/utils/ModbusTypes.h src/utils/Logger.h src/utils/Settings.h src/utils/DataLogger.h 3rdparty/libmodbus/src/modbus.h src/imodbus.h src/tcpipsettingswidget.h src/ipaddressctrl.h src/iplineedit.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/DeviceConfigDialog.cpp src/core/ModbusDevice.cpp src/core/ModbusRegister.cpp src/core/ModbusConnection.cpp src/ui/ConnectionSettingsWidget.cpp src/ui/RegisterTableModel.cpp src/ui/RegisterSetupDialog.cpp src/utils/Logger.cpp src/utils/Settings.cpp src/utils/DataLogger.cpp 3rdparty/libmodbus/src/modbus.c 3rdparty/libmodbus/src/modbus-data.c 3rdparty/libmodbus/src/modbus-tcp.c src/tcpipsettingswidget.cpp src/ipaddressctrl.cpp src/iplineedit.cpp $(DISTDIR)/
	$(COPY_FILE) --parents forms/mainwindow.ui forms/ConnectionSettingsWidget.ui forms/RegisterSetupDialog.ui forms/tcpipsettingswidget.ui forms/ipaddressctrl.ui forms/DeviceConfigDialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qmodbus.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qmodbus.cpp
qrc_qmodbus.cpp: data/qmodbus.qrc \
		/usr/lib/qt5/bin/rcc \
		data/logo.png
	/usr/lib/qt5/bin/rcc -name qmodbus data/qmodbus.qrc -o qrc_qmodbus.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	x86_64-linux-gnu-g++ -pipe -g -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_DeviceConfigDialog.cpp moc_ModbusDevice.cpp moc_ModbusRegister.cpp moc_ModbusConnection.cpp moc_ConnectionSettingsWidget.cpp moc_RegisterTableModel.cpp moc_RegisterSetupDialog.cpp moc_Logger.cpp moc_Settings.cpp moc_DataLogger.cpp moc_tcpipsettingswidget.cpp moc_ipaddressctrl.cpp moc_iplineedit.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_DeviceConfigDialog.cpp moc_ModbusDevice.cpp moc_ModbusRegister.cpp moc_ModbusConnection.cpp moc_ConnectionSettingsWidget.cpp moc_RegisterTableModel.cpp moc_RegisterSetupDialog.cpp moc_Logger.cpp moc_Settings.cpp moc_DataLogger.cpp moc_tcpipsettingswidget.cpp moc_ipaddressctrl.cpp moc_iplineedit.cpp
moc_mainwindow.cpp: src/mainwindow.h \
		ui_mainwindow.h \
		3rdparty/libmodbus/src/modbus.h \
		3rdparty/libmodbus/src/modbus-version.h \
		3rdparty/libmodbus/src/modbus-tcp.h \
		src/DeviceConfigDialog.h \
		3rdparty/libmodbus/src/deviceconfig.h \
		src/utils/DataLogger.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mengin/İndirilenler/qmodbus-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mengin/İndirilenler/qmodbus-master -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus/src -I/home/mengin/İndirilenler/qmodbus-master/src -I/home/mengin/İndirilenler/qmodbus-master/src/core -I/home/mengin/İndirilenler/qmodbus-master/src/ui -I/home/mengin/İndirilenler/qmodbus-master/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/mainwindow.h -o moc_mainwindow.cpp

moc_DeviceConfigDialog.cpp: src/DeviceConfigDialog.h \
		3rdparty/libmodbus/src/deviceconfig.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mengin/İndirilenler/qmodbus-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mengin/İndirilenler/qmodbus-master -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus/src -I/home/mengin/İndirilenler/qmodbus-master/src -I/home/mengin/İndirilenler/qmodbus-master/src/core -I/home/mengin/İndirilenler/qmodbus-master/src/ui -I/home/mengin/İndirilenler/qmodbus-master/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/DeviceConfigDialog.h -o moc_DeviceConfigDialog.cpp

moc_ModbusDevice.cpp: src/core/ModbusDevice.h \
		src/core/ModbusConnection.h \
		src/utils/ModbusTypes.h \
		src/imodbus.h \
		3rdparty/libmodbus/src/modbus.h \
		3rdparty/libmodbus/src/modbus-version.h \
		3rdparty/libmodbus/src/modbus-tcp.h \
		src/core/ModbusRegister.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mengin/İndirilenler/qmodbus-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mengin/İndirilenler/qmodbus-master -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus/src -I/home/mengin/İndirilenler/qmodbus-master/src -I/home/mengin/İndirilenler/qmodbus-master/src/core -I/home/mengin/İndirilenler/qmodbus-master/src/ui -I/home/mengin/İndirilenler/qmodbus-master/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/core/ModbusDevice.h -o moc_ModbusDevice.cpp

moc_ModbusRegister.cpp: src/core/ModbusRegister.h \
		src/utils/ModbusTypes.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mengin/İndirilenler/qmodbus-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mengin/İndirilenler/qmodbus-master -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus/src -I/home/mengin/İndirilenler/qmodbus-master/src -I/home/mengin/İndirilenler/qmodbus-master/src/core -I/home/mengin/İndirilenler/qmodbus-master/src/ui -I/home/mengin/İndirilenler/qmodbus-master/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/core/ModbusRegister.h -o moc_ModbusRegister.cpp

moc_ModbusConnection.cpp: src/core/ModbusConnection.h \
		src/utils/ModbusTypes.h \
		src/imodbus.h \
		3rdparty/libmodbus/src/modbus.h \
		3rdparty/libmodbus/src/modbus-version.h \
		3rdparty/libmodbus/src/modbus-tcp.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mengin/İndirilenler/qmodbus-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mengin/İndirilenler/qmodbus-master -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus/src -I/home/mengin/İndirilenler/qmodbus-master/src -I/home/mengin/İndirilenler/qmodbus-master/src/core -I/home/mengin/İndirilenler/qmodbus-master/src/ui -I/home/mengin/İndirilenler/qmodbus-master/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/core/ModbusConnection.h -o moc_ModbusConnection.cpp

moc_ConnectionSettingsWidget.cpp: src/ui/ConnectionSettingsWidget.h \
		src/utils/ModbusTypes.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mengin/İndirilenler/qmodbus-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mengin/İndirilenler/qmodbus-master -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus/src -I/home/mengin/İndirilenler/qmodbus-master/src -I/home/mengin/İndirilenler/qmodbus-master/src/core -I/home/mengin/İndirilenler/qmodbus-master/src/ui -I/home/mengin/İndirilenler/qmodbus-master/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/ui/ConnectionSettingsWidget.h -o moc_ConnectionSettingsWidget.cpp

moc_RegisterTableModel.cpp: src/ui/RegisterTableModel.h \
		src/utils/ModbusTypes.h \
		src/core/ModbusRegister.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mengin/İndirilenler/qmodbus-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mengin/İndirilenler/qmodbus-master -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus/src -I/home/mengin/İndirilenler/qmodbus-master/src -I/home/mengin/İndirilenler/qmodbus-master/src/core -I/home/mengin/İndirilenler/qmodbus-master/src/ui -I/home/mengin/İndirilenler/qmodbus-master/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/ui/RegisterTableModel.h -o moc_RegisterTableModel.cpp

moc_RegisterSetupDialog.cpp: src/ui/RegisterSetupDialog.h \
		src/utils/ModbusTypes.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mengin/İndirilenler/qmodbus-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mengin/İndirilenler/qmodbus-master -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus/src -I/home/mengin/İndirilenler/qmodbus-master/src -I/home/mengin/İndirilenler/qmodbus-master/src/core -I/home/mengin/İndirilenler/qmodbus-master/src/ui -I/home/mengin/İndirilenler/qmodbus-master/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/ui/RegisterSetupDialog.h -o moc_RegisterSetupDialog.cpp

moc_Logger.cpp: src/utils/Logger.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mengin/İndirilenler/qmodbus-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mengin/İndirilenler/qmodbus-master -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus/src -I/home/mengin/İndirilenler/qmodbus-master/src -I/home/mengin/İndirilenler/qmodbus-master/src/core -I/home/mengin/İndirilenler/qmodbus-master/src/ui -I/home/mengin/İndirilenler/qmodbus-master/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/utils/Logger.h -o moc_Logger.cpp

moc_Settings.cpp: src/utils/Settings.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mengin/İndirilenler/qmodbus-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mengin/İndirilenler/qmodbus-master -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus/src -I/home/mengin/İndirilenler/qmodbus-master/src -I/home/mengin/İndirilenler/qmodbus-master/src/core -I/home/mengin/İndirilenler/qmodbus-master/src/ui -I/home/mengin/İndirilenler/qmodbus-master/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/utils/Settings.h -o moc_Settings.cpp

moc_DataLogger.cpp: src/utils/DataLogger.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mengin/İndirilenler/qmodbus-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mengin/İndirilenler/qmodbus-master -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus/src -I/home/mengin/İndirilenler/qmodbus-master/src -I/home/mengin/İndirilenler/qmodbus-master/src/core -I/home/mengin/İndirilenler/qmodbus-master/src/ui -I/home/mengin/İndirilenler/qmodbus-master/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/utils/DataLogger.h -o moc_DataLogger.cpp

moc_tcpipsettingswidget.cpp: src/tcpipsettingswidget.h \
		src/imodbus.h \
		3rdparty/libmodbus/src/modbus.h \
		3rdparty/libmodbus/src/modbus-version.h \
		3rdparty/libmodbus/src/modbus-tcp.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mengin/İndirilenler/qmodbus-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mengin/İndirilenler/qmodbus-master -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus/src -I/home/mengin/İndirilenler/qmodbus-master/src -I/home/mengin/İndirilenler/qmodbus-master/src/core -I/home/mengin/İndirilenler/qmodbus-master/src/ui -I/home/mengin/İndirilenler/qmodbus-master/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/tcpipsettingswidget.h -o moc_tcpipsettingswidget.cpp

moc_ipaddressctrl.cpp: src/ipaddressctrl.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mengin/İndirilenler/qmodbus-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mengin/İndirilenler/qmodbus-master -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus/src -I/home/mengin/İndirilenler/qmodbus-master/src -I/home/mengin/İndirilenler/qmodbus-master/src/core -I/home/mengin/İndirilenler/qmodbus-master/src/ui -I/home/mengin/İndirilenler/qmodbus-master/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/ipaddressctrl.h -o moc_ipaddressctrl.cpp

moc_iplineedit.cpp: src/iplineedit.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mengin/İndirilenler/qmodbus-master/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mengin/İndirilenler/qmodbus-master -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus -I/home/mengin/İndirilenler/qmodbus-master/3rdparty/libmodbus/src -I/home/mengin/İndirilenler/qmodbus-master/src -I/home/mengin/İndirilenler/qmodbus-master/src/core -I/home/mengin/İndirilenler/qmodbus-master/src/ui -I/home/mengin/İndirilenler/qmodbus-master/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/iplineedit.h -o moc_iplineedit.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_ConnectionSettingsWidget.h ui_RegisterSetupDialog.h ui_tcpipsettingswidget.h ui_ipaddressctrl.h ui_DeviceConfigDialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_ConnectionSettingsWidget.h ui_RegisterSetupDialog.h ui_tcpipsettingswidget.h ui_ipaddressctrl.h ui_DeviceConfigDialog.h
ui_mainwindow.h: forms/mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic forms/mainwindow.ui -o ui_mainwindow.h

ui_ConnectionSettingsWidget.h: forms/ConnectionSettingsWidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic forms/ConnectionSettingsWidget.ui -o ui_ConnectionSettingsWidget.h

ui_RegisterSetupDialog.h: forms/RegisterSetupDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic forms/RegisterSetupDialog.ui -o ui_RegisterSetupDialog.h

ui_tcpipsettingswidget.h: forms/tcpipsettingswidget.ui \
		/usr/lib/qt5/bin/uic \
		src/ipaddressctrl.h
	/usr/lib/qt5/bin/uic forms/tcpipsettingswidget.ui -o ui_tcpipsettingswidget.h

ui_ipaddressctrl.h: forms/ipaddressctrl.ui \
		/usr/lib/qt5/bin/uic \
		src/iplineedit.h
	/usr/lib/qt5/bin/uic forms/ipaddressctrl.ui -o ui_ipaddressctrl.h

ui_DeviceConfigDialog.h: forms/DeviceConfigDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic forms/DeviceConfigDialog.ui -o ui_DeviceConfigDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp src/mainwindow.h \
		ui_mainwindow.h \
		3rdparty/libmodbus/src/modbus.h \
		3rdparty/libmodbus/src/modbus-version.h \
		3rdparty/libmodbus/src/modbus-tcp.h \
		src/DeviceConfigDialog.h \
		3rdparty/libmodbus/src/deviceconfig.h \
		src/utils/DataLogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		ui_mainwindow.h \
		3rdparty/libmodbus/src/modbus.h \
		3rdparty/libmodbus/src/modbus-version.h \
		3rdparty/libmodbus/src/modbus-tcp.h \
		src/DeviceConfigDialog.h \
		3rdparty/libmodbus/src/deviceconfig.h \
		src/utils/DataLogger.h \
		src/ui/RegisterTableModel.h \
		src/utils/ModbusTypes.h \
		src/core/ModbusRegister.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

DeviceConfigDialog.o: src/DeviceConfigDialog.cpp src/DeviceConfigDialog.h \
		3rdparty/libmodbus/src/deviceconfig.h \
		ui_DeviceConfigDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DeviceConfigDialog.o src/DeviceConfigDialog.cpp

ModbusDevice.o: src/core/ModbusDevice.cpp src/core/ModbusDevice.h \
		src/core/ModbusConnection.h \
		src/utils/ModbusTypes.h \
		src/imodbus.h \
		3rdparty/libmodbus/src/modbus.h \
		3rdparty/libmodbus/src/modbus-version.h \
		3rdparty/libmodbus/src/modbus-tcp.h \
		src/core/ModbusRegister.h \
		src/utils/Logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ModbusDevice.o src/core/ModbusDevice.cpp

ModbusRegister.o: src/core/ModbusRegister.cpp src/core/ModbusRegister.h \
		src/utils/ModbusTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ModbusRegister.o src/core/ModbusRegister.cpp

ModbusConnection.o: src/core/ModbusConnection.cpp src/core/ModbusConnection.h \
		src/utils/ModbusTypes.h \
		src/imodbus.h \
		3rdparty/libmodbus/src/modbus.h \
		3rdparty/libmodbus/src/modbus-version.h \
		3rdparty/libmodbus/src/modbus-tcp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ModbusConnection.o src/core/ModbusConnection.cpp

ConnectionSettingsWidget.o: src/ui/ConnectionSettingsWidget.cpp src/ui/ConnectionSettingsWidget.h \
		src/utils/ModbusTypes.h \
		ui_ConnectionSettingsWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ConnectionSettingsWidget.o src/ui/ConnectionSettingsWidget.cpp

RegisterTableModel.o: src/ui/RegisterTableModel.cpp src/ui/RegisterTableModel.h \
		src/utils/ModbusTypes.h \
		src/core/ModbusRegister.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RegisterTableModel.o src/ui/RegisterTableModel.cpp

RegisterSetupDialog.o: src/ui/RegisterSetupDialog.cpp src/ui/RegisterSetupDialog.h \
		src/utils/ModbusTypes.h \
		ui_RegisterSetupDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RegisterSetupDialog.o src/ui/RegisterSetupDialog.cpp

Logger.o: src/utils/Logger.cpp src/utils/Logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Logger.o src/utils/Logger.cpp

Settings.o: src/utils/Settings.cpp src/utils/Settings.h \
		src/utils/Logger.h \
		src/utils/ModbusTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Settings.o src/utils/Settings.cpp

DataLogger.o: src/utils/DataLogger.cpp src/utils/DataLogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DataLogger.o src/utils/DataLogger.cpp

modbus.o: 3rdparty/libmodbus/src/modbus.c 3rdparty/libmodbus/config.h \
		3rdparty/libmodbus/src/modbus.h \
		3rdparty/libmodbus/src/modbus-version.h \
		3rdparty/libmodbus/src/modbus-tcp.h \
		3rdparty/libmodbus/src/modbus-private.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o modbus.o 3rdparty/libmodbus/src/modbus.c

modbus-data.o: 3rdparty/libmodbus/src/modbus-data.c 3rdparty/libmodbus/src/modbus.h \
		3rdparty/libmodbus/src/modbus-version.h \
		3rdparty/libmodbus/src/modbus-tcp.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o modbus-data.o 3rdparty/libmodbus/src/modbus-data.c

modbus-tcp.o: 3rdparty/libmodbus/src/modbus-tcp.c 3rdparty/libmodbus/src/modbus-private.h \
		3rdparty/libmodbus/config.h \
		3rdparty/libmodbus/src/modbus.h \
		3rdparty/libmodbus/src/modbus-version.h \
		3rdparty/libmodbus/src/modbus-tcp.h \
		3rdparty/libmodbus/src/modbus-tcp-private.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o modbus-tcp.o 3rdparty/libmodbus/src/modbus-tcp.c

tcpipsettingswidget.o: src/tcpipsettingswidget.cpp src/tcpipsettingswidget.h \
		src/imodbus.h \
		3rdparty/libmodbus/src/modbus.h \
		3rdparty/libmodbus/src/modbus-version.h \
		3rdparty/libmodbus/src/modbus-tcp.h \
		ui_tcpipsettingswidget.h \
		src/ipaddressctrl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpipsettingswidget.o src/tcpipsettingswidget.cpp

ipaddressctrl.o: src/ipaddressctrl.cpp src/ipaddressctrl.h \
		ui_ipaddressctrl.h \
		src/iplineedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ipaddressctrl.o src/ipaddressctrl.cpp

iplineedit.o: src/iplineedit.cpp src/iplineedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iplineedit.o src/iplineedit.cpp

qrc_qmodbus.o: qrc_qmodbus.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qmodbus.o qrc_qmodbus.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_DeviceConfigDialog.o: moc_DeviceConfigDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DeviceConfigDialog.o moc_DeviceConfigDialog.cpp

moc_ModbusDevice.o: moc_ModbusDevice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ModbusDevice.o moc_ModbusDevice.cpp

moc_ModbusRegister.o: moc_ModbusRegister.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ModbusRegister.o moc_ModbusRegister.cpp

moc_ModbusConnection.o: moc_ModbusConnection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ModbusConnection.o moc_ModbusConnection.cpp

moc_ConnectionSettingsWidget.o: moc_ConnectionSettingsWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ConnectionSettingsWidget.o moc_ConnectionSettingsWidget.cpp

moc_RegisterTableModel.o: moc_RegisterTableModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_RegisterTableModel.o moc_RegisterTableModel.cpp

moc_RegisterSetupDialog.o: moc_RegisterSetupDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_RegisterSetupDialog.o moc_RegisterSetupDialog.cpp

moc_Logger.o: moc_Logger.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Logger.o moc_Logger.cpp

moc_Settings.o: moc_Settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Settings.o moc_Settings.cpp

moc_DataLogger.o: moc_DataLogger.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DataLogger.o moc_DataLogger.cpp

moc_tcpipsettingswidget.o: moc_tcpipsettingswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcpipsettingswidget.o moc_tcpipsettingswidget.cpp

moc_ipaddressctrl.o: moc_ipaddressctrl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ipaddressctrl.o moc_ipaddressctrl.cpp

moc_iplineedit.o: moc_iplineedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_iplineedit.o moc_iplineedit.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/local/bin || mkdir -p $(INSTALL_ROOT)/usr/local/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/local/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/local/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

